[package]
name = "play_stack"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "0.8.2"
audio_graph = { path = "../audio_graph" }
audio_modules = { path = "../audio_modules" }
audio_stack = { path = "../audio_stack" }
