[package]
name = "audio_stack"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"

[dependencies]
audio_graph = { path = "../audio_graph" }
audio_modules = { path = "../audio_modules" }
rand = "0.6.5"
